namespace Downlism.Core.Downloads;

/// <summary>
/// Decides which engine a link belongs to.
/// </summary>
/// <remarks>
/// A person pasting a link does not think in engines, and asking them to pick one would be
/// asking them to know what a manifest is. The rules below are the small set that can be
/// decided from the URL alone and are wrong rarely enough to be worth applying silently; the
/// extension can still override the answer, because it saw the response headers and this did
/// not.
/// </remarks>
public static class TransferRouting
{
    public const string MagnetScheme = "magnet";

    /// <summary>
    /// Streaming manifests. Handing one of these to the HTTP engine downloads a playlist of a
    /// few kilobytes and calls it a video, which is the single most confusing thing a download
    /// manager can do.
    /// </summary>
    private static readonly string[] ManifestExtensions = [".m3u8", ".m3u", ".mpd", ".f4m", ".ism"];

    /// <summary>
    /// Sites whose video URLs are generated by a player and are worthless on their own. Only
    /// the page address can be downloaded, so the page address is what gets routed. The list is
    /// deliberately short — it exists to catch the handful of sites people paste by habit, not
    /// to duplicate the thousand extractors yt-dlp already has.
    /// </summary>
    private static readonly string[] MediaHosts =
    [
        "youtube.com", "youtu.be", "vimeo.com", "dailymotion.com", "twitch.tv",
        "bilibili.com", "nicovideo.jp", "tiktok.com", "twitter.com", "x.com",
        "facebook.com", "instagram.com", "soundcloud.com", "bandcamp.com",
        "reddit.com", "streamable.com", "odysee.com", "rumble.com",
    ];

    public static TransferKind For(Uri uri)
    {
        if (uri.Scheme == MagnetScheme) return TransferKind.Torrent;

        var path = uri.IsAbsoluteUri && uri.Scheme is "http" or "https" ? uri.AbsolutePath : string.Empty;

        if (path.EndsWith(".torrent", StringComparison.OrdinalIgnoreCase)) return TransferKind.Torrent;

        foreach (var extension in ManifestExtensions)
        {
            if (path.EndsWith(extension, StringComparison.OrdinalIgnoreCase)) return TransferKind.Media;
        }

        return IsMediaHost(uri) ? TransferKind.Media : TransferKind.Http;
    }

    /// <summary>Matches the registrable domain, so www. and m. and a country subdomain all count.</summary>
    public static bool IsMediaHost(Uri uri)
    {
        if (uri.Scheme is not ("http" or "https")) return false;

        var host = uri.Host;
        foreach (var known in MediaHosts)
        {
            if (host.Equals(known, StringComparison.OrdinalIgnoreCase)) return true;
            if (host.EndsWith("." + known, StringComparison.OrdinalIgnoreCase)) return true;
        }

        return false;
    }

    /// <summary>Accepts the schemes any of the three engines can actually start from.</summary>
    public static bool TryParse(string? text, out Uri uri)
    {
        // Written out rather than as a pattern: Uri.UriSchemeHttp is a static field, not a
        // constant, so it cannot appear in one.
        if (Uri.TryCreate(text?.Trim(), UriKind.Absolute, out var parsed)
            && (parsed.Scheme == Uri.UriSchemeHttp
                || parsed.Scheme == Uri.UriSchemeHttps
                || parsed.Scheme == MagnetScheme))
        {
            uri = parsed;
            return true;
        }

        uri = null!;
        return false;
    }

    /// <summary>
    /// A readable name for a link that has none. A magnet carries a display name in its
    /// <c>dn</c> parameter; without one there is nothing but the info hash, and showing a row
    /// labelled with forty hex characters is worse than showing none.
    /// </summary>
    public static string? NameFromMagnet(Uri uri)
    {
        if (uri.Scheme != MagnetScheme) return null;

        // Magnet links are opaque URIs: the query sits in the path, not in Query.
        var text = uri.OriginalString;
        var start = text.IndexOf('?');
        if (start < 0) return null;

        foreach (var pair in text[(start + 1)..].Split('&'))
        {
            if (!pair.StartsWith("dn=", StringComparison.OrdinalIgnoreCase)) continue;

            try
            {
                var name = Uri.UnescapeDataString(pair[3..].Replace('+', ' ')).Trim();
                return name.Length == 0 ? null : name;
            }
            catch (UriFormatException)
            {
                return null;
            }
        }

        return null;
    }
}
