<Project Sdk="Microsoft.NET.Sdk">
 <PropertyGroup>
  <OutputType>WinExe</OutputType>
  <ApplicationIcon>..\..\docs\assets\downlism.ico</ApplicationIcon>
  <AssemblyName>Downlism.Install</AssemblyName>
  <RuntimeIdentifier>win-x64</RuntimeIdentifier>
  <SelfContained>true</SelfContained>
  <PublishSingleFile>false</PublishSingleFile>
  <DebugType>embedded</DebugType>
  <ApplicationManifest>..\Downlism.App\app.manifest</ApplicationManifest>
 </PropertyGroup>
</Project>
